import 'package:flutter/material.dart';
import 'package:ionicons/ionicons.dart';


// const IconData mailIcon = Ionicons.mail;
// const IconData call = Icons.call;
// const IconData passwordLock = Ionicons.lock_closed_outline;
// const IconData obscureText = Ionicons.eye_outline;
const IconData menuIcon = Icons.more_vert;
const IconData user = Icons.person_2_outlined;
const IconData backarrow = Icons.arrow_back;
const IconData attachments = Icons.attach_file;
const IconData currency = Icons.currency_rupee_sharp;
const IconData send = Icons.send;
const IconData editIcon = Icons.edit;
const IconData clearIcon = Icons.close;
const IconData dashboardIcon = Icons.house_outlined;
const IconData expandedIcon = Icons.expand_more_outlined;
const IconData downloadIcon = Icons.picture_as_pdf;
const IconData cancelIcon = Icons.cancel_outlined;
const IconData humbergerIcon = Icons.menu;
const IconData trashIcon = Icons.delete;
const IconData verticleDot = Icons.more_vert;
const IconData addIcon = Icons.add_outlined;
 const IconData globeIcon = Ionicons.globe_outline;
const IconData logout = Icons.logout;
 const IconData carIcon = Ionicons.car;
const IconData cameraIcon = Icons.camera;
 const IconData additonalIcon = Ionicons.add_circle_outline;
const IconData rotate = Icons.rotate_90_degrees_ccw;
const IconData estimateIcon = Icons.file_copy_sharp;
const IconData invoiceIcon = Icons.article_rounded;
const IconData uparrow = Icons.arrow_upward_rounded;
const IconData downarrow = Icons.arrow_downward;
 const IconData favIcon = Ionicons.heart;
 const IconData whatsappIcon = Ionicons.logo_whatsapp;
const IconData imageNotSupport = Icons.image_not_supported_outlined;
const IconData mailIcon = Icons.mail_outline;
const IconData call= Icons.call;

